### ISSUE TITLE
Could not create directory '/home/sbx_user1070/.ssh'.

### ISSUE THREAD

**Issue by x1angli** [lambci/git-lambda-layer#10]
while running ssh command , it shows sth like

`Could not create directory '/home/sbx_user1070/.ssh'.`

I guess this is related to AWS Lambda's read-only file system.

Even with the `HOME` env var set to something like `/tmp/home/` the error message is still there..

Not sure if it matters . But anyway the error msg bothers me  -_| :rofl:

**Comment by mhart** [comment]
This is explained in the README: https://github.com/lambci/git-lambda-layer#complex-example-on-nodejs-w-ssh
