### ISSUE TITLE
SSH git clone broken - missing libldap2.4

### ISSUE THREAD

**Issue by Richard-Payne** [lambci/git-lambda-layer#14]
I've added your git layer's v6 and copied the sample lambda code, replacing the known_hosts, rsa key and git repo url with my own.  I get the following error:

`ssh: error while loading shared libraries: libldap-2.4.so.2: cannot open shared object file: No such file or directory`

May or may not be relevant, but our git repo is hosted in a TFS VCS server.

**Comment by mhart** [comment]
Hey! Which runtime are you using?

**Comment by Richard-Payne** [comment]
NodeJs 10

**Comment by Richard-Payne** [comment]
Just re-read the readme.  I misread it the first time apparently.  

Switched the lambda to NodeJs 8.10 and get this:

```
START RequestId: d2270df8-6925-4922-b2ed-9857ca1d7237 Version: $LATEST
2019-10-02T12:27:23.873Z	d2270df8-6925-4922-b2ed-9857ca1d7237	{"errorMessage":"Command failed: git clone ssh://tfs.company.com:22/tfs/Production/_git/terraform-haproxy /tmp/terraform-haproxy","errorType":"Error","stackTrace":["checkExecSyncError (child_process.js:601:13)","execSync (child_process.js:641:13)","exports.handler (/var/task/index.js:43:3)"]}
END RequestId: d2270df8-6925-4922-b2ed-9857ca1d7237
REPORT RequestId: d2270df8-6925-4922-b2ed-9857ca1d7237	Duration: 243.34 ms	Billed Duration: 300 ms	Memory Size: 128 MB	Max Memory Used: 73 MB	
```

I'm either going blind or there's no useful error in there. :(

**Comment by mhart** [comment]
Well that's just the way you're invoking git with Node.js. I'm sure if you did something like:

```js
execSync('git clone ...', { stdio: 'inherit' })
```

You'd be able to see the error (and I'm sure it's to do with SSH keys). See https://github.com/lambci/git-lambda-layer#complex-example-on-nodejs-w-ssh for how you might need to setup your SSH

**Comment by Richard-Payne** [comment]
ok, so this is what I'm using:
```
execSync('git clone ssh://tfs.company.com:22/tfs/Production/_git/terraform-haproxy /tmp/terraform-haproxy', { encoding: 'utf8', stdio: 'inherit' })
return execSync('ls /tmp/terraform-haproxy', { encoding: 'utf8' }).split('\n')
```
This returns null:
`return execSync('git --version', { encoding: 'utf8', stdio: 'inherit' })`

**Comment by mhart** [comment]
Yes, it will return null. That's how `stdio: 'inherit'` works – it outputs to stdout/stderr instead of returning. But then you can see the logs and so you'll be able to see where your problem is.

It doesn't look like you're specifying any ssh keys, so I'm pretty sure your ssh command won't work.

Unless there's an issue with this layer, then I'm going to close this issue

**Comment by Richard-Payne** [comment]
Yeah, didn't include the whole as it's just your sample code with the known_hosts, key and url changed.

**Comment by mhart** [comment]
Ok, well in that example I use `stdio: 'inherit'` for the git clone command, and that will output any errors to the logs, so you can see them in CloudWatch

**Comment by Richard-Payne** [comment]
ah ok, I see.  I left the stdio: inherit part in but nothing is going to CloudWatch

**Comment by Richard-Payne** [comment]
So I just did a straight clone from a public repo to rule out ssh config issues.

`execSync('git clone https://github.com/phpredis/phpredis.git /tmp/terraform-haproxy', { encoding: 'utf8', stdio: 'inherit' })`

That times out after 3 seconds.  I'm assuming that if no explicit VPC is set then the lambda has internet access.  Is that correct?

**Comment by mhart** [comment]
I mean, it might be that the exception is killing the process before it has a chance to get the logs. You could try: 
```js
child_process.spawnSync('git', ['clone', 'ssh://tfs.company.com:22/tfs/Production/_git/terraform-haproxy', '/tmp/terraform-haproxy'], {stdio: 'inherit'})
```

instead (and then check the logs)

**Comment by mhart** [comment]
When you say it times out after 3 seconds – do you mean you've only got a 3 second timeout for your Lambda? (in which case, increase it) Or that the git process exits after 3 seconds?

**Comment by Richard-Payne** [comment]
ok, I've worked out the CloudWatch issue.  It was an IAM role issue.  

The git problem is that it can't resolve the hostname, which is odd because it resolves fine from other hosts in the vpc.

Anyway, I think it's safe to say that this is no longer your issue. Thankyou for your help. Much appreciated.

**Comment by mhart** [comment]
No probs, good luck!
