### ISSUE TITLE
Python3.8: Error while loading shared libraries: libcurl

### ISSUE THREAD

**Issue by JeremyRitchie** [lambci/git-lambda-layer#16]
Hi, I've noticed that the git-lambda-layer does not work with python3.8. It does work fine with 3.6, i have not tested 3.7. 

Error:
Cloning into '/tmp/repo'...
/opt/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

Cheers

EDIT:

It works fine on both 3.6 and 3.7.

**Comment by mhart** [comment]
You'll need to use the `git-lambda2` because python3.8 uses the same new OS as `nodejs10.x` (and now `nodejs12.x` and `java11`). I'll update the README accordingly

**Comment by JeremyRitchie** [comment]
Ah great!
Thanks very much.
