### ISSUE TITLE
Lambda nodejs10.x warning: templates not found in /tmp/git/usr/share/git-core/templates

### ISSUE THREAD

**Issue by WinstonN** [lambci/git-lambda-layer#17]
Hi :)

I'm trying to get this layer working in my lambda
I'm using serverless and have added the later to my function

```
layers:
      - arn:aws:lambda:${opt:region}:553035198032:layer:git-lambda2:3
```
When I try to clone a https:// git repo I get the error

```
warning: templates not found in /tmp/git/usr/share/git-core/templates
```

I can see git binaries in /opt/bin
```
2019-12-17T11:08:11.860Z	7fee8550-01f8-4f1e-8d25-da11de063fae	INFO	log gitBinaryDir contents
2019-12-17T11:08:11.860Z	7fee8550-01f8-4f1e-8d25-da11de063fae	INFO	fipscheck
fipshmac
git
git-receive-pack
git-shell
git-upload-archive
git-upload-pack
idn2
scp
sftp
slogin
ssh
ssh-add
ssh-agent
ssh-copy-id
ssh-keygen
ssh-keyscan
xmlwf
```

but I also see this env vars in my lambda env
```
GIT_TEMPLATE_DIR: '/tmp/git/usr/share/git-core/templates',
GIT_EXEC_PATH: '/tmp/git/usr/libexec/git-core',
```

The question I have is. What is the true location of the templates, so that I can set them correctly in my lambda environment?

Thanks again, for all the good work here, and please keep it up!

**Comment by mhart** [comment]
Hey there. What made you set those environment variables?

If you remove them, it should work fine.

**Comment by WinstonN** [comment]
@mhart - I found where those ENV vars were being set, and removing them got it kicking over
Thanks for pointing that out

**Comment by mhart** [comment]
Can you give me some background about where those env vars were being set? Was it another project setting them (and if so, which one)?

**Comment by WinstonN** [comment]
@mhart sure. I'm working on a project that gathered dust for a while, and initially, we placed git on the lambdas by using https://github.com/pimterry/lambda-git and setting those env vars in the serverless.yml under the environment section - that worked when we used node 8

moving to node 10.x I got the error:
```
git: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
```
and in trying to solve it I came across this project

I also tried https://www.npmjs.com/package/lambda-git but even with the vars set, I couldn't get that to work either (i think it was just late in the evening, and I was tired)

Thanks again for the assistance, and let me know if you need more information

**Comment by mhart** [comment]
Gotcha, thanks for the info 👍 Should help if I ever see ppl come across the same error
