### ISSUE TITLE
Nodejs12 doesn't seem to be working with layer v3?

### ISSUE THREAD

**Issue by daisieh** [lambci/git-lambda-layer#18]
I tried to attach the layer as instructed in the readme (arn:aws:lambda:us-west-2:553035198032:layer:git-lambda2:3), and it seems to be there, but when I run my lambda, I get the following error still: 

```
git clone: Cloning into 'route53_monitoring_check'...
/tmp/git/usr/libexec/git-core/git-remote-https: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
```

I'm sorry if I'm missing something exceptionally obvious, but I'm just not seeing what I missed. Can you help me figure this out? Thanks!

**Comment by mhart** [comment]
I'm a bit confused – why are you executing `/tmp/git/usr/libexec/git-core/git-remote-https`?

That sounds like you have something in `/tmp/git` – this layer doesn't mount anything in `/tmp`

Can you provide a way to reproduce this? Are you using some sort of third party library?

**Comment by daisieh** [comment]
Ha, while trying to reproduce this, I noticed a line in the export.handler that was causing it:

`await require('lambda-git')();`

I think that was the cause. Sorry to bother, and thanks for replying!
