### ISSUE TITLE
Lambda nodejs12.x - Permission denied (Public Key) 

### ISSUE THREAD

**Issue by Revlig** [lambci/git-lambda-layer#19]
Hi everyone :D

I'm trying to get this layer working in my lambda
I'm using serverless and have added the layer to my function

![image](https://user-images.githubusercontent.com/31891672/74367744-25fb5580-4db1-11ea-9ba0-e0a94ae046e5.png)

I'm using nodejs12.x and Git version 2.25.0 | OpenSSH_7.4p1, OpenSSL 1.0.2k-fips and the copy  of the example "Complex example on Node.js w/ ssh"  with my private key hardcoded in the file:

![image](https://user-images.githubusercontent.com/31891672/74368444-6a3b2580-4db2-11ea-902f-4119c24f42d3.png)

I generated a new private and public key and tested them previously, but in my logs in the CloudWatch i got:

![image](https://user-images.githubusercontent.com/31891672/74368658-d9187e80-4db2-11ea-9498-c8db1b1e76ba.png)

I tried many ways to resolve, but I failed.
Anyway, congrats for the amazing work!
Thanks :)

**Comment by mhart** [comment]
Hi @Revlig, not sure how to help you here – the error you're getting is a permission error, not a problem with this layer, so it's probably just the way you've set things up.

Try doing this instead of using the known hosts file, just in case that's the issue:

```js
process.env.GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa'
```

If not, the only other thing I can think is that you might not have pasted the private key correctly – just make sure it includes all the newlines, etc as it does in the example in the README.

**Comment by Revlig** [comment]
Sorry about that, I will check the settings :)
Again, thanks for your time :D

**Comment by qianxitu** [comment]
> Sorry about that, I will check the settings :)
> Again, thanks for your time :D

Hi Revlig, I met the exact same issue and I have been stuck for 1 day. Did you figure it out at the end? 

> Hi everyone :D
> 
> I'm trying to get this layer working in my lambda
> I'm using serverless and have added the layer to my function
> 
> ![image](https://user-images.githubusercontent.com/31891672/74367744-25fb5580-4db1-11ea-9ba0-e0a94ae046e5.png)
> 
> I'm using nodejs12.x and Git version 2.25.0 | OpenSSH_7.4p1, OpenSSL 1.0.2k-fips and the copy of the example "Complex example on Node.js w/ ssh" with my private key hardcoded in the file:
> 
> ![image](https://user-images.githubusercontent.com/31891672/74368444-6a3b2580-4db2-11ea-902f-4119c24f42d3.png)
> 
> I generated a new private and public key and tested them previously, but in my logs in the CloudWatch i got:
> 
> ![image](https://user-images.githubusercontent.com/31891672/74368658-d9187e80-4db2-11ea-9498-c8db1b1e76ba.png)
> 
> I tried many ways to resolve, but I failed.
> Anyway, congrats for the amazing work!
> Thanks :)

Hi Revlig, I met the exact same issue and I have been stuck for 1 day. Did you figure it out at the end?

**Comment by qianxitu** [comment]
> Hi everyone :D
> 
> I'm trying to get this layer working in my lambda
> I'm using serverless and have added the layer to my function
> 
> ![image](https://user-images.githubusercontent.com/31891672/74367744-25fb5580-4db1-11ea-9ba0-e0a94ae046e5.png)
> 
> I'm using nodejs12.x and Git version 2.25.0 | OpenSSH_7.4p1, OpenSSL 1.0.2k-fips and the copy of the example "Complex example on Node.js w/ ssh" with my private key hardcoded in the file:
> 
> ![image](https://user-images.githubusercontent.com/31891672/74368444-6a3b2580-4db2-11ea-902f-4119c24f42d3.png)
> 
> I generated a new private and public key and tested them previously, but in my logs in the CloudWatch i got:
> 
> ![image](https://user-images.githubusercontent.com/31891672/74368658-d9187e80-4db2-11ea-9498-c8db1b1e76ba.png)
> 
> I tried many ways to resolve, but I failed.
> Anyway, congrats for the amazing work!
> Thanks :)

Hi Revlig, I met the exact same issue and I have been stuck for 1 day. Did you figure it out at the end?
