### ISSUE TITLE
Could you add the build process?

### ISSUE THREAD

**Issue by tijoer** [lambci/git-lambda-layer#20]
Hi,

this is a nice idea. Thanks for the project.

However it seems to be working with binary files inside a .zip archive. Could you also opensource the build process for the zip file, so that users don't need to execute binary files on their production environment?

I also want to build this myself, so that I don't have to rely on a arbitrary aws account, that could go offline someday :D.

With kind regards,
Tim

**Comment by mhart** [comment]
It's all open – the zip files are built using https://github.com/lambci/git-lambda-layer/blob/master/lambda1/build.sh and https://github.com/lambci/git-lambda-layer/blob/master/lambda2/build.sh

**Comment by tijoer** [comment]
Thank you very much für your time. This helped me a lot, as I rarely worked with docker. I spend the last day creating some own docker images now and I am beginning to understand how this works. :)

However you seem to use your own Docker image lambci/yumda which does most of the magic here. In the build process of lambci/yumda you use the following command: 

curl https://lambci.s3.amazonaws.com/fs/base-2.tgz | tar -xz -C /lambda

This seems kinda strange, as this file contains binary files.

**Comment by mhart** [comment]
Those binary files come from Lambda. AWS doesn't release docker images for the Lambda – the only way to replicate the Lambda environment is to do it yourself. That tarball is produced by the https://github.com/lambci/docker-lambda project, which AWS themselves use in the AWS SAM CLI.

You can create your own Lambda-like environment if you don't want to copy over binaries from Lambda. Start with https://github.com/amazonlinux/container-images/blob/93b9c7974ab6ddd65abace3bf68c20005e5ee82a/Dockerfile and then remove/add the same packages as what exist on Lambda. Of course, the tarball in that docker image still contains binary files, which you find strange, so if you didn't want that, then you'll need to create your own amazon linux docker image from scratch.
