### ISSUE TITLE
Cannot load PCRE

### ISSUE THREAD

**Issue by wookieb** [lambci/git-lambda-layer#23]
Unfortunatelly I got this error when trying to use git in real AWS Lambda
```/opt/bin/git: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory```

**Runtime**:
nodejs12.x

**Used layer**:
arn:aws:lambda:eu-central-1:553035198032:layer:git-lambda2:6

**Comment by mhart** [comment]
Are you using any other layers or modifying any environment variables?

**Comment by wookieb** [comment]
No sir :)

git-lambda2 is the only layer used

The only ENV variable I do set is "AWS_NODEJS_CONNECTION_REUSE_ENABLED=1"

**Comment by mhart** [comment]
How are you executing `git`? Is it just like in the README, or are you perhaps not inheriting env variables?

Can you add this to your lambda somewhere?

```js
const { execSync } = require('child_process')
console.log(execSync('ls -l /opt/lib/libpcre2*', {encoding: 'utf8'}))
console.log(process.env.LD_LIBRARY_PATH)
```

**Comment by wookieb** [comment]
My friend. This is it! I was using `simple-git` and it didn't inherit env from process. 
Adding `git().env(process.env)` helped!

Thank You so much! :)

**Comment by mhart** [comment]
Ah, you should've said! Ok, glad you solved the issue
