### ISSUE TITLE
AccessDeniedException on Gov Cloud?

### ISSUE THREAD

**Issue by tinyvogon** [lambci/git-lambda-layer#24]
Hi, I'm trying to run git on my lambda function which is on us-gov-west-1, but got an error saying I was unauthorized to perform GetLayer action on the layer's resource arn although my user's IAM policy already covers Lambda. I'm wondering if the resource is available in my region or not. I've tried using the layer on the commercial environment and it works perfectly, so I'm not sure if I'm missing anything... I'd really appreciate your help!

**Comment by mhart** [comment]
You're right, it's not available in us-gov-west-1. I don't think I even have access to that region? Do normal AWS users have access to gov regions?

**Comment by tinyvogon** [comment]
I'm not sure, it's for my work.. Do you think it's possible for me to make your layer into a custom lambda layer?

**Comment by mhart** [comment]
Oh totally, you can see the zip files in https://github.com/lambci/git-lambda-layer/tree/master/lambda2 or https://github.com/lambci/git-lambda-layer/tree/master/lambda1 (depending on which runtime you're using)

You can deploy that zip file to your own Layer using `aws lambda publish-layer-version`  or using the AWS web UI. https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by tinyvogon** [comment]
That works! Thank you so much!
