### ISSUE TITLE
Could not deploy because lambda with layer exceeded 250 mb...

### ISSUE THREAD

**Issue by nectario** [lambci/git-lambda-layer#27]
An error occurred: TrainUnderscoreminorLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 263669938 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: b05441bc-77f9-4416-b9b0-3625bfe59d64).

I had to use number 5 instead of 13 for it to work.

**Comment by mhart** [comment]
The layer itself is only 43MB – so you'd only get that failure if you had ~200MB of other files in your Lambda

**Comment by nectario** [comment]
43 MB is a lot if we only have 250 MB in our lambda space to squeeze in all our dependencies. If the older version worked for me, it means maybe you guys reduce a bit it's size?

**Comment by mhart** [comment]
The older version would've only worked by mere chance – newer versions are larger because git is adding more features

You can submit a PR against git if you'd like to reduce its size
