### ISSUE TITLE
Permission Denied and File Too Short errors for git and ssh

### ISSUE THREAD

**Issue by yevk** [lambci/git-lambda-layer#3]
Running `git` in lambda, I get `/bin/sh: /opt/bin/git: Permission denied`.

Using `docker run` to get interactive shell, I get the same error trying to run git: `sh: /opt/bin/git: Permission denied`.
The problem seems to be the lack of execution permission on files in /opt/bin:
`-rw-rw-rw- 1 sbx_user1051 495 2480144 Dec 24 20:24 git`
`-rw-rw-rw- 1 sbx_user1051 495  658056 Dec 24 20:24 ssh`

Granting permission using `chmod +x /opt/bin/*` fixes this problem.
But, `ssh` still doesn't work due to another error: `ssh: error while loading shared libraries: /opt/lib/libfipscheck.so.1: file too short`, not sure why.

I tested this on an image created and cached by AWS SAM CLI after attempting to locally invoke the lambda.

**Comment by mhart** [comment]
This must be an issue with your setup. You can verify that the git binary is executable by doing the following:

```console
$ git clone --depth 1 https://github.com/lambci/git-lambda-layer
$ cd git-lambda-layer
$ unzip layer.zip -d opt
$ ls -l opt/bin/git
-rwxr-xr-x  1 michael  staff  2480144  9 Dec 15:22 git
```

**Comment by mhart** [comment]
Out of interest – which ARN are you using? It might be that a specific region got corrupted or similar?

**Comment by mhart** [comment]
I've just checked all regions, and all have the same file length (11949741), so it's unlikely that any are corrupted

Can you please outline the steps you took to reproduce the error?

**Comment by yevk** [comment]
Using `arn:aws:lambda:us-west-1:553035198032:layer:git:3`

I added Layers property with the ARN above to a function in a SAM yaml file.
Then invoked the function using SAM CLI.
My function failed with the permission error so I connected to the container:
`docker run -it --entrypoint=/bin/sh samcli/lambda:nodejs8.10-14d28d937c892d6e5399dc210`

**Comment by mhart** [comment]
This is definitely an issue with your setup then. Maybe your `umask` or similar. Or something with Docker. I don't know what image `samcli/lambda` is.

In any case, it's nothing to do with this repository.

**Comment by yevk** [comment]
Ok, thank you. I'll figure it out.

**Comment by mhart** [comment]
You can try this to see if it works:

```
docker run --rm lambci/lambda:build-provided sh -c 'cd /tmp && git clone --depth 1 https://github.com/lambci/git-lambda-layer && cd git-lambda-layer && unzip -q layer.zip -d /opt && ls -l /opt/bin/git'
```
Should output:
```
-rwxr-xr-x 1 root root 2480144 Dec  9 20:22 /opt/bin/git
```
