### ISSUE TITLE
Unable to include from CLI

### ISSUE THREAD

**Issue by romaninsh** [lambci/git-lambda-layer#4]
While I was able to attach the layer using AWS console, the same thing cannot be done from the command-line:

```
rw$ aws lambda update-function-configuration --function-name gitsync --layers arn:aws:lambda:us-east-1:553035198032:layer:git:3

An error occurred (AccessDeniedException) when calling the UpdateFunctionConfiguration operation: User: arn:aws:iam::123132123:user/romaninsh is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:553035198032:layer:git:3
```

user "romaninsh" is full admin.

**Comment by mhart** [comment]
I suspect this must be an issue with your user permissions – the layer itself allows `lambda:GetLayerVersion` to be called from any Principal.

Try adding the `lambda:GetLayerVersion` permissions to the user explicitly and see if that works:

https://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html#permissions-resources-layers

**Comment by silviulucian** [comment]
Experiencing the same when deploying from Serverless

```
User: arn:aws:iam::886182114158:user/silviulucian-alt is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:553035198032:layer:git:3 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: ebbb27dc-0d1b-11e9-b997-7b10317a7e42).
```

As with romaninsh's account above, this user is a

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

**Comment by mhart** [comment]
Well if it works from the AWS console, then I think everything must be fine on the layer end – so I still suspect it's some sort of permissions issue on your end.

Do you have the same problem with any other layers? eg, https://github.com/RafalWilinski/serverless-puppeteer-layers

**Comment by silviulucian** [comment]
Aaaa, right, I feel silly I didn't check to see if it worked with another layer first. Same error. I'll keep digging and get back when I figured it out.

**Comment by silviulucian** [comment]
Alrighty, figured it out: I copied and pasted the layer arn blindly and kept us-east-1 in there as the region. My lambda is deployed in eu-west-1 however. Everything started chooching just fine once I changed the region in the layer arn to match the one I was using.

**Comment by romaninsh** [comment]
@silviulucian I am also deployed in EU region. Thanks for the possible fix idea!

**Comment by mhart** [comment]
This is documented under the ARNs: https://github.com/lambci/git-lambda-layer#version-arns

I might add it to the getting started too

**Comment by romaninsh** [comment]
Yes was confused because the same ARN worked the same.
