### ISSUE TITLE
Could not resolve hostname

### ISSUE THREAD

**Issue by schwiet** [lambci/git-lambda-layer#7]
I'm running exactly your second example (substituting my own key and repo) and hitting this error:

`ssh: Could not resolve hostname github.com:myorganization: Name or service not known`

my key and known_hosts file appear fine, I can run

`ssh -T git@github`
and get
`Hi schwiet! You've successfully authenticated, but GitHub does not provide shell access.`

One thing, I noticed is that it seems the documented environment variable is [GIT_SSH](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) and not `GIT_SSH_COMMAND`, but unfortunately changing that did not resolve the problem.

**Comment by mhart** [comment]
`github.com:myorganization` looks like you haven't specified the host correctly, like maybe you've done `ssh://git@github.com:myorganization/myproject.git` instead of `ssh://git@github.com/myorganization/myproject.git`

**Comment by mhart** [comment]
Also, `GIT_SSH` and `GIT_SSH_COMMAND` aren't quite the same thing – in this case we need `GIT_SSH_COMMAND` so that we can include extra args. See:

https://git-scm.com/docs/git#git-codeGITSSHCOMMANDcode

**Comment by schwiet** [comment]
@mhart thank you! yes, you are right, I was using the `ssh_url` directly from the webhooks event, which has the form `git@github.com:myorganization/myproject.git`, replacing the ":" with "/" restored order. Though, it's not clear to me why `git clone git@github.com:myorganization/myproject.git` works on my local machine but not in the lambda 🤔
