### ISSUE TITLE
known_hosts and id_rsa

### ISSUE THREAD

**Issue by x1angli** [lambci/git-lambda-layer#8]
Great job! Thank you LambCI

 just curious

The example file shows that it dynamically creates two files,  known_hosts and id_rsa under the "/tmp" folder
Would it be easier to create and deploy a separate AWS layer (that layer would only contain these two files) , so that these two files will always be there in the "/opt" directory ...
coz AWS supports up to 5 layers at the same time.

Question: 
Not so sure if we still need to run `chmod 400` in this case. Do you think it would be necessary?

**Comment by mhart** [comment]
Private keys need to certain permissions otherwise ssh will ignore them:

https://unix.stackexchange.com/questions/257590/ssh-key-permissions-chmod-settings

It would be fine to upload known_hosts in another layer (or just in the function package itself)

**Comment by x1angli** [comment]
got it. thank you very much!

**Comment by x1angli** [comment]
follow up , FYI:
Sad news
it seems we still need to fall back to /tmp folder, since everything else is read only in AWS Lambda....
